---
name: Main Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "docs/**"

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup workspace
        uses: ./.github/actions/setup-workspace

      - name: Install linters
        run: |
          pip install --upgrade pip
          pip install pre-commit==3.5.0

      - name: Install dependencies
        run: |
          just tidy
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/fzipp/gocyclo/cmd/gocyclo@latest

      - name: Run linters
        run: pre-commit run --all-files --verbose

  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run setup
        uses: ./.github/actions/setup-workspace

      - name: Run Go tests
        run: |
          go clean -testcache
          go test -v -cover -race ./...

      - name: Run Python tests
        run: |
          uv run pytest -vv

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run setup
        uses: ./.github/actions/setup-workspace

      - name: Build binary
        run: |
          just tidy
          just build

      - name: Run binary
        run: |
          ./devops --help
